model:
  base_learning_rate: 4.5e-06
  target: taming.models.vqgan.VQModel
  params:
    image_key: nucleus
    monitor: 
    ckpt_path: 
    embed_dim: 256
    n_embed: 512
    ddconfig:
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 1
        disc_start: 50000
        disc_weight: 0.2
        codebook_weight: 1.0

data:
  target: celle_main.CellDataModule
  params:
    data_csv: 
    crop_size: 256
    batch_size: 1
    num_workers: 8
